### ISSUE TITLE
Jar does not seem to be published to maven central

### ISSUE THREAD

**Issue by kell05** [aileftech/spring-boot-database-admin#18]
**Describe the bug**
Would it be possible to publish this code to maven central? It's a requirement for the setting which I want to use the code.

I am happy to pick up any work required to accomplish this.

**Comment by aileftech** [comment]
I don't understand this, as the code should be already published, I can see the artifacts here:

https://central.sonatype.com/artifact/tech.ailef/spring-boot-db-admin

And also indexed correctly on the mvnrepository:

https://mvnrepository.com/artifact/tech.ailef/spring-boot-db-admin

Am I missing something?

**Comment by kell05** [comment]
Apologies I was looking under spring-boot-database-admin rather than spring-boot-db-admin.
