### ISSUE TITLE
Fix ClassLoader interaction with Spring Boot Devtools 

### ISSUE THREAD

**Issue by aileftech** [aileftech/spring-boot-database-admin#8]
If devtools are included in the project, they inject a custom ClassLoader that interferes with the correct initialization of the EntityManager (see #1).

The current solution is not to include Spring Boot Devtools in order to run the project. Check what would be needed to fix this issue and restore compatibility with devtools.

**Comment by odrotbohm** [comment]
I think the only thing you need to do to fix this is telling Devtools, that it should include your JAR with the class loader that loads application classes by adding a `META-INF/spring-devtools.properties`. A project that needed to do something similar can be found [here](https://github.com/st-tu-dresden/salespoint/blob/main/src/main/resources/META-INF/spring-devtools.properties).

**Comment by aileftech** [comment]
Thanks! I've just tested this and it works perfectly. I'll include it in the next release.
